# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4cb4ae0f26fb5a093d2737d2093ef5ec7b9e800c04ddb50c7714e7967d06fa0e26361d05fd5e57da2a15b6b98193b98eb27e51868660264e7b4419874fec2c3

test:
  secret_key_base: c8cb7614943246ab076598c62927b4219275d5d20112dae66e92b70fda7e0649b62587ca5de721c116cb462ba151fe97c27f474478ca977e6fe5657f082d7147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
